const AppError = require('../utils/AppError');

function escapeCsv(value) {
  const normalized = value === null || value === undefined ? '' : String(value);
  return `"${normalized.replace(/"/g, '""')}"`;
}

function toCsvBuffer({ companyName, reportName, dateRangeLabel, generatedBy, generatedAt, filters, totals, columns, rows }) {
  const headerLines = [
    ['Company', companyName || 'AptusOS'],
    ['Report', reportName || 'Finance Report'],
    ['Date range', dateRangeLabel || 'All time'],
    ['Generated by', generatedBy || 'System'],
    ['Generated at', generatedAt || new Date().toISOString()],
    ['Filters', JSON.stringify(filters || {})],
    ['Totals', JSON.stringify(totals || {})],
    []
  ];

  const lines = [
    ...headerLines.map((line) => line.length ? line.map(escapeCsv).join(',') : ''),
    (columns || []).map(escapeCsv).join(','),
    ...(rows || []).map((row) => (columns || []).map((column) => escapeCsv(row[column])).join(','))
  ];

  return Buffer.from(lines.join('\n'), 'utf8');
}

function toSimpleHtml({ companyName, reportName, generatedBy, generatedAt, filters, totals, columns, rows }) {
  const th = (columns || []).map((column) => `<th style="text-align:left;padding:8px;border:1px solid #ddd;">${column}</th>`).join('');
  const tr = (rows || []).map((row) => {
    const cells = (columns || []).map((column) => `<td style="padding:8px;border:1px solid #eee;">${row[column] ?? ''}</td>`).join('');
    return `<tr>${cells}</tr>`;
  }).join('');

  return `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>${reportName || 'Finance report'}</title>
  </head>
  <body style="font-family:Arial,sans-serif;">
    <h1>${companyName || 'AptusOS'} - ${reportName || 'Finance report'}</h1>
    <p><strong>Generated by:</strong> ${generatedBy || 'System'}<br/><strong>Generated at:</strong> ${generatedAt || new Date().toISOString()}</p>
    <p><strong>Filters:</strong> ${JSON.stringify(filters || {})}</p>
    <p><strong>Totals:</strong> ${JSON.stringify(totals || {})}</p>
    <table style="border-collapse:collapse;width:100%;">
      <thead><tr>${th}</tr></thead>
      <tbody>${tr}</tbody>
    </table>
  </body>
</html>`;
}

const exportService = {
  buildExport(report, format = 'csv') {
    const normalized = String(format || 'csv').toLowerCase();
    const reportName = String(report.reportType || 'finance-report').replace(/-/g, ' ');

    if (normalized === 'csv') {
      return {
        mimeType: 'text/csv; charset=utf-8',
        extension: 'csv',
        content: toCsvBuffer({
          companyName: 'AptusOS',
          reportName,
          dateRangeLabel: report.filters?.dateFrom || report.filters?.dateTo
            ? `${report.filters?.dateFrom || 'start'} to ${report.filters?.dateTo || 'today'}`
            : 'All time',
          generatedBy: report.generatedBy?.fullName || report.generatedBy?.email || 'System',
          generatedAt: report.generatedAt,
          filters: report.filters,
          totals: report.totals,
          columns: report.columns,
          rows: report.rows
        })
      };
    }

    if (normalized === 'print') {
      return {
        mimeType: 'text/html; charset=utf-8',
        extension: 'html',
        content: Buffer.from(toSimpleHtml({
          companyName: 'AptusOS',
          reportName,
          generatedBy: report.generatedBy?.fullName || report.generatedBy?.email || 'System',
          generatedAt: report.generatedAt,
          filters: report.filters,
          totals: report.totals,
          columns: report.columns,
          rows: report.rows
        }), 'utf8')
      };
    }

    if (normalized === 'excel' || normalized === 'xlsx' || normalized === 'pdf') {
      throw new AppError(`${normalized.toUpperCase()} export is coming soon`, 501);
    }

    throw new AppError('Unsupported export format', 400);
  }
};

module.exports = exportService;
