const ROLES = Object.freeze({
  GENERAL_MANAGER: 'GENERAL_MANAGER',
  DEPARTMENT_HEAD: 'DEPARTMENT_HEAD',
  HR_MANAGER: 'HR_MANAGER',
  FINANCE_ACCOUNTS_MANAGER: 'FINANCE_ACCOUNTS_MANAGER',
  SALES_COMPLIANCE_OFFICER: 'SALES_COMPLIANCE_OFFICER',
  OPERATIONS_PROCUREMENT_OFFICER: 'OPERATIONS_PROCUREMENT_OFFICER',
  EMPLOYEE: 'EMPLOYEE'
});

const LEGACY_ROLE_ALIASES = Object.freeze({
  FINANCE_MANAGER: ROLES.FINANCE_ACCOUNTS_MANAGER,
  ACCOUNTS_OFFICER: ROLES.FINANCE_ACCOUNTS_MANAGER,
  SALES_COMPLIANCE: ROLES.SALES_COMPLIANCE_OFFICER,
  HRMANAGER: ROLES.HR_MANAGER,
  FINANCEMANAGER: ROLES.FINANCE_ACCOUNTS_MANAGER,
  OPSMANAGER: ROLES.OPERATIONS_PROCUREMENT_OFFICER
});

const normalizeRoleName = (roleName) => LEGACY_ROLE_ALIASES[roleName] || roleName;

module.exports = { ROLES, LEGACY_ROLE_ALIASES, normalizeRoleName };
