ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'MESSAGE_READ';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'MESSAGE_EMAIL_DELIVERED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'MESSAGE_EMAIL_FAILED';
