ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'STAFF_ONBOARDING_EMAIL_SENT';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'STAFF_ONBOARDING_EMAIL_FAILED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'STAFF_CREDENTIALS_RESENT';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'STAFF_CREDENTIALS_RESEND_FAILED';
